language: python
python:
  - "3.8"
  - "2.7"
before_install:
  # To install bats and test our shell/bash functions
  - sudo add-apt-repository ppa:duggan/bats --yes
  - sudo apt-get update -qq
  - sudo apt-get install -qq bats
  - sudo apt-get install -qq zsh

# For bats functional tests
env:
  - functional_test="true"

# command to install dependencies
install: "pip install ."

# command to run tests
script:
  - bats tests/shell
  - py.test

notifications:
  email:
    on_success: never
