name: Bashhub Client

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "2.7"]

    env:
      functional_test: true
      CI_UNSUPPORTED: true

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install python dependencies and bats
      run: |
        pip install .
        pip install pytest
        sudo apt-get update
        sudo apt-get install -y bats

    - name: Test with pytest
      run: |
        pytest

    - name: Test with bats
      run: |
        bats tests/shell
